#if canImport(SwiftUI)
  @available(iOS 13.0, OSX 10.15, tvOS 13.0, watchOS 6.0, *)
  /// All of these supported devices
  ///
  /// More reference could be found at: <https://developer.apple.com/documentation/swiftui/view/previewdevice(_:)>
  public extension DefinedPreviewDevices {
    enum Device: String, CaseIterable {
      case mac = "Mac"
      case macCatalyst = "Mac Catalyst"

      // MARK: Generated code start
      case iPhone4s = "iPhone 4s"
      case iPhone5 = "iPhone 5"
      case iPhone5s = "iPhone 5s"
      case iPhone6Plus = "iPhone 6 Plus"
      case iPhone6 = "iPhone 6"
      case iPhone6s = "iPhone 6s"
      case iPhone6sPlus = "iPhone 6s Plus"
      case iPhoneSE1stGeneration = "iPhone SE (1st generation)"
      case iPhone7 = "iPhone 7"
      case iPhone7Plus = "iPhone 7 Plus"
      case iPhone8 = "iPhone 8"
      case iPhone8Plus = "iPhone 8 Plus"
      case iPhoneX = "iPhone X"
      case iPhoneXs = "iPhone Xs"
      case iPhoneXsMax = "iPhone Xs Max"
      case iPhoneXʀ = "iPhone Xʀ"
      case iPhone11 = "iPhone 11"
      case iPhone11Pro = "iPhone 11 Pro"
      case iPhone11ProMax = "iPhone 11 Pro Max"
      case iPhoneSE2ndGeneration = "iPhone SE (2nd generation)"
      case iPhone12Mini = "iPhone 12 mini"
      case iPhone12 = "iPhone 12"
      case iPhone12Pro = "iPhone 12 Pro"
      case iPhone12ProMax = "iPhone 12 Pro Max"
      case iPodTouch7thGeneration = "iPod touch (7th generation)"
      case iPad2 = "iPad 2"
      case iPadRetina = "iPad Retina"
      case iPadAir = "iPad Air"
      case iPadMini2 = "iPad mini 2"
      case iPadMini3 = "iPad mini 3"
      case iPadMini4 = "iPad mini 4"
      case iPadAir2 = "iPad Air 2"
      case iPadPro9_7inch = "iPad Pro (9_7-inch)"
      case iPadPro12_9inch1stGeneration = "iPad Pro (12_9-inch) (1st generation)"
      case iPad5thGeneration = "iPad (5th generation)"
      case iPadPro12_9inch2ndGeneration = "iPad Pro (12_9-inch) (2nd generation)"
      case iPadPro10_5inch = "iPad Pro (10_5-inch)"
      case iPad6thGeneration = "iPad (6th generation)"
      case iPad7thGeneration = "iPad (7th generation)"
      case iPadPro11inch1stGeneration = "iPad Pro (11-inch) (1st generation)"
      case iPadPro12_9inch3rdGeneration = "iPad Pro (12_9-inch) (3rd generation)"
      case iPadPro11inch2ndGeneration = "iPad Pro (11-inch) (2nd generation)"
      case iPadPro12_9inch4thGeneration = "iPad Pro (12_9-inch) (4th generation)"
      case iPadMini5thGeneration = "iPad mini (5th generation)"
      case iPadAir3rdGeneration = "iPad Air (3rd generation)"
      case iPad8thGeneration = "iPad (8th generation)"
      case iPadAir4thGeneration = "iPad Air (4th generation)"
      case iPadPro11inch3rdGeneration = "iPad Pro (11-inch) (3rd generation)"
      case iPadPro12_9inch5thGeneration = "iPad Pro (12_9-inch) (5th generation)"
      case appleTV = "Apple TV"
      case appleTV4K = "Apple TV 4K"
      case appleTV4KAt1080p = "Apple TV 4K (at 1080p)"
      case appleTV4K2ndGeneration = "Apple TV 4K (2nd generation)"
      case appleTV4KAt1080p2ndGeneration = "Apple TV 4K (at 1080p) (2nd generation)"
      case appleWatch38mm = "Apple Watch - 38mm"
      case appleWatch42mm = "Apple Watch - 42mm"
      case appleWatchSeries2_38mm = "Apple Watch Series 2 - 38mm"
      case appleWatchSeries2_42mm = "Apple Watch Series 2 - 42mm"
      case appleWatchSeries3_38mm = "Apple Watch Series 3 - 38mm"
      case appleWatchSeries3_42mm = "Apple Watch Series 3 - 42mm"
      case appleWatchSeries4_40mm = "Apple Watch Series 4 - 40mm"
      case appleWatchSeries4_44mm = "Apple Watch Series 4 - 44mm"
      case appleWatchSeries5_40mm = "Apple Watch Series 5 - 40mm"
      case appleWatchSeries5_44mm = "Apple Watch Series 5 - 44mm"
      case appleWatchSE40mm = "Apple Watch SE - 40mm"
      case appleWatchSE44mm = "Apple Watch SE - 44mm"
      case appleWatchSeries6_40mm = "Apple Watch Series 6 - 40mm"
      case appleWatchSeries6_44mm = "Apple Watch Series 6 - 44mm"
      // MARK: Generated code end
    }
  }
#endif
